apiVersion: v1
kind: Pod
metadata:
  name: ollama-pod
spec:
  restartPolicy: Always
  containers:
    - name: ollama
      image: ollama/ollama:latest
      ports:
        - containerPort: 11434
      volumeMounts:
        - name: ollama-volume
          mountPath: /root/.ollama
      tty: true

    - name: ollama-webui
      image: ghcr.io/ollama-webui/ollama-webui:main
      ports:
        - containerPort: 8080
      volumeMounts:
        - name: ollama-webui-volume
          mountPath: /app/backend/data
      env:
        - name: OLLAMA_API_BASE_URL
          value: "http://localhost:11434/api"
      # Note: Kubernetes does not have a direct equivalent to Docker's network_mode: "host"
      # You may need to configure a Service or use host networking separately if required.

  volumes:
    - name: ollama-volume
      emptyDir: {}  # Use emptyDir for ephemeral storage; adjust as needed.
    - name: ollama-webui-volume
      emptyDir: {}  # Use emptyDir for ephemeral storage; adjust as needed.
